services:
  app:
    container_name: asbensisantri_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      CI_ENVIRONMENT: production
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_KEY: ${APP_KEY}
      WA_NOTIFICATION: ${WA_NOTIFICATION}
      WHATSAPP_PROVIDER: ${WHATSAPP_PROVIDER}
      WAHA_API_URL: ${WAHA_API_URL}
      WHATSAPP_TOKEN: ${WHATSAPP_TOKEN}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: ${APP_TIMEZONE}
    depends_on:
      - db
    networks:
      - asbensi_net

  db:
    image: mariadb:10.11
    container_name: asbensisantri_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - asbensi_net

  adminer:
    image: adminer:latest
    container_name: asbensisantri_adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - asbensi_net

networks:
  asbensi_net:
    driver: bridge